name: Claim address

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Claim IP and commit 
      run: |
        curl http://108.61.215.240/claim?name=ghrmbell -o claim.html
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add claim.html
        timestamp=$(date -u)
        address=$(python -c "import re
        with open('claim.html') as f:
          regex = r'land at ((?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))'
          text = f.read()
          matches = re.findall(regex, text)

        if matches:
          print(matches[0])
        else:
          print('<not found>')")

        git commit -m "Got IP address ${address} at ${timestamp}"
        git push
